### ISSUE TITLE
not enough values to unpack

### ISSUE THREAD

**Issue by Ella77** [polm/ndl-crop#2]
result = function(*positional, **keywords)
  File "test1.py", line 114, in autocrop_image
    contours = get_contours(img)
  File "test1.py", line 35, in get_contours
    img2, contours, hierarchy = cv2.findContours(thresh, 1, 2)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by polm** [comment]
I think your error is due to a change in function signature in OpenCV v4, which was not released when I wrote this code. I suggest you use OpenCV 3 as specified in `requirements.txt`.  

If this error occurs with the version specified in `requirements.txt` then that needs fixing, but since I assume this is due to a version mismatch I am closing this for now.
